"""Helpers for Alembic / MSSQL migrations (FK drop order, legacy tables).

SQL Server errors with **3726** when ``DROP TABLE`` runs while another table still has a
foreign key referencing it. Autogenerated migrations often emit ``drop_table`` in an
unsafe order — call :func:`alembic_drop_foreign_keys_referencing_tables` at the start of
``upgrade()`` before dropping legacy tables such as ``invoices`` / ``invoice_lines``.

Error **3728** ("is not a constraint") happens when a migration tries to ``DROP CONSTRAINT``
that was already removed or never existed. Use :func:`mssql_drop_fk_if_exists` from a
revision or the ``flask prepare-mssql-legacy-fks`` command.
"""

from __future__ import annotations

from typing import Iterable


def mssql_drop_fk_if_exists(engine, *, table: str, constraint_name: str) -> bool:
    """Drop a single foreign key on ``table`` if it exists. Returns whether a drop ran."""
    from sqlalchemy import text

    dialect = (engine.dialect.name or "").lower()
    if "mssql" not in dialect:
        return False

    q = text(
        """
        SELECT s.name AS sch, t.name AS tbl, fk.name AS fkname
        FROM sys.foreign_keys fk
        INNER JOIN sys.tables t ON fk.parent_object_id = t.object_id
        INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
        WHERE LOWER(fk.name) = LOWER(:fkname) AND t.name = :tbl
        """
    )
    with engine.begin() as conn:
        row = conn.execute(q, {"fkname": constraint_name, "tbl": table}).mappings().first()
        if not row:
            return False
        sch, tbl, fkname = row["sch"], row["tbl"], row["fkname"]
        conn.execute(text(f"ALTER TABLE [{sch}].[{tbl}] DROP CONSTRAINT [{fkname}]"))
    return True


def _mssql_drop_fks_referencing_named_tables(engine, referred_table_names: set[str]) -> int:
    """Drop every FK whose *referenced* table is one of ``referred_table_names`` (MSSQL ``sys``)."""
    from sqlalchemy import text

    if not referred_table_names:
        return 0

    # Table names are fixed literals from our code paths only (not user input).
    in_sql = ", ".join("'" + n.replace("'", "") + "'" for n in sorted(referred_table_names))
    select_sql = f"""
        SELECT fk.name AS fk_name,
               ps.name AS parent_schema,
               pt.name AS parent_table
        FROM sys.foreign_keys fk
        INNER JOIN sys.tables rt ON fk.referenced_object_id = rt.object_id
        INNER JOIN sys.tables pt ON fk.parent_object_id = pt.object_id
        INNER JOIN sys.schemas ps ON pt.schema_id = ps.schema_id
        WHERE rt.name IN ({in_sql})
    """

    dropped_total = 0
    for _ in range(200):
        with engine.begin() as conn:
            rows = conn.execute(text(select_sql)).mappings().all()
            if not rows:
                return dropped_total
            r0 = rows[0]
            fk_name, sch, tbl = r0["fk_name"], r0["parent_schema"], r0["parent_table"]
            conn.execute(text(f"ALTER TABLE [{sch}].[{tbl}] DROP CONSTRAINT [{fk_name}]"))
            dropped_total += 1
    return dropped_total


def alembic_drop_foreign_keys_referencing_tables(op, referred_tables: Iterable[str]) -> None:
    """Drop all FK constraints that reference any of ``referred_tables`` (MSSQL-aware)."""
    from sqlalchemy import inspect

    targets = {t for t in referred_tables if t}
    if not targets:
        return

    bind = op.get_bind()
    dialect = (bind.dialect.name or "").lower()
    if "mssql" in dialect:
        # Use sys catalog (more reliable than inspector for referenced-table direction).
        eng = getattr(bind, "engine", bind)
        _mssql_drop_fks_referencing_named_tables(eng, targets)
        return

    for _ in range(200):
        insp = inspect(bind)
        dropped = False
        for tbl in list(insp.get_table_names()):
            try:
                fks = insp.get_foreign_keys(tbl)
            except Exception:
                continue
            for fk in fks:
                ref = fk.get("referred_table")
                if ref in targets:
                    name = fk.get("name")
                    if name:
                        op.drop_constraint(name, tbl, type_="foreignkey")
                        dropped = True
                        break
            if dropped:
                break
        if not dropped:
            return


def engine_drop_foreign_keys_referencing_tables(engine, referred_tables: Iterable[str]) -> int:
    """Drop FKs referencing ``referred_tables``. Returns number of constraints dropped."""
    dialect = (engine.dialect.name or "").lower()
    targets = {t for t in referred_tables if t}
    if not targets:
        return 0

    if "mssql" in dialect:
        return _mssql_drop_fks_referencing_named_tables(engine, targets)

    from sqlalchemy import inspect, text

    dropped_total = 0
    for _ in range(200):
        insp = inspect(engine)
        found: tuple[str, str] | None = None
        for tbl in list(insp.get_table_names()):
            try:
                fks = insp.get_foreign_keys(tbl)
            except Exception:
                continue
            for fk in fks:
                if fk.get("referred_table") in targets and fk.get("name"):
                    found = (tbl, fk["name"])
                    break
            if found:
                break
        if not found:
            break
        tbl, cname = found
        with engine.begin() as conn:
            conn.execute(text(f"ALTER TABLE [{tbl}] DROP CONSTRAINT [{cname}]"))
        dropped_total += 1
    return dropped_total


def prepare_mssql_legacy_invoice_fks(engine) -> dict[str, int | bool]:
    """Run from ``flask prepare-mssql-legacy-fks``: drop invoice FKs + known legacy names.

    Only **constraint** objects are removed (foreign keys, default ``DF_*``), never ``DROP TABLE``
    or ``DELETE`` — members, agents, contributions (payments), and other application data tables
    are untouched.
    """
    dialect = (engine.dialect.name or "").lower()
    if "mssql" not in dialect:
        return {
            "skipped": True,
            "parent_to_invoices": 0,
            "from_referenced": 0,
            "known_named": 0,
            "defaults_for_alter": 0,
        }

    n0 = mssql_drop_fk_parent_to_referred_table_if_exists(
        engine, parent_table="contributions", referred_table="invoices", schema="dbo"
    )
    n1 = engine_drop_foreign_keys_referencing_tables(engine, ("invoice_lines", "invoices"))
    n2 = 0
    # Autogenerate often names this FK explicitly; it may already be gone (3728).
    if mssql_drop_fk_if_exists(engine, table="contributions", constraint_name="FK_contributions_invoice"):
        n2 += 1
    n3 = engine_mssql_drop_defaults_that_block_datetime2_alter(engine)
    return {
        "skipped": False,
        "parent_to_invoices": n0,
        "from_referenced": n1,
        "known_named": n2,
        "defaults_for_alter": n3,
    }


def alembic_mssql_drop_fk_if_exists(op, *, table: str, constraint_name: str) -> bool:
    """Call from a revision before ``batch_op.drop_constraint(...)`` if the FK may already be gone."""
    bind = op.get_bind()
    return mssql_drop_fk_if_exists(bind.engine, table=table, constraint_name=constraint_name)


def mssql_drop_fk_parent_to_referred_table_if_exists(
    engine, *, parent_table: str, referred_table: str, schema: str = "dbo"
) -> int:
    """Drop every foreign key on ``parent_table`` that points at ``referred_table`` (MSSQL)."""
    from sqlalchemy import text

    if "mssql" not in (engine.dialect.name or "").lower():
        return 0

    q = text(
        """
        SELECT fk.name AS fkname,
               s.name AS sch, pt.name AS ptab
        FROM sys.foreign_keys fk
        INNER JOIN sys.tables pt ON fk.parent_object_id = pt.object_id
        INNER JOIN sys.schemas s ON pt.schema_id = s.schema_id
        INNER JOIN sys.tables rt ON fk.referenced_object_id = rt.object_id
        WHERE s.name = :schema AND pt.name = :p AND rt.name = :r
        """
    )
    n = 0
    for _ in range(50):
        with engine.begin() as conn:
            row = conn.execute(
                q, {"schema": schema, "p": parent_table, "r": referred_table}
            ).mappings().first()
            if not row:
                return n
            cname, sch, tbl = row["fkname"], row["sch"], row["ptab"]
            conn.execute(text(f"ALTER TABLE [{sch}].[{tbl}] DROP CONSTRAINT [{cname}]"))
        n += 1
    return n


def alembic_mssql_drop_fk_parent_to_referred_if_exists(
    op, *, parent_table: str, referred_table: str, schema: str = "dbo"
) -> int:
    eng = op.get_bind().engine
    return mssql_drop_fk_parent_to_referred_table_if_exists(
        eng, parent_table=parent_table, referred_table=referred_table, schema=schema
    )


def mssql_drop_default_constraint_on_column_if_exists(
    engine, *, table: str, column: str, schema: str = "dbo"
) -> bool:
    """MSSQL: default constraints block ``ALTER COLUMN`` — drop the ``DF_...`` first."""
    from sqlalchemy import text

    if "mssql" not in (engine.dialect.name or "").lower():
        return False

    q = text(
        """
        SELECT dc.name
        FROM sys.default_constraints dc
        INNER JOIN sys.columns c
            ON dc.parent_object_id = c.object_id AND c.column_id = dc.parent_column_id
        INNER JOIN sys.tables t ON c.object_id = t.object_id
        INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
        WHERE s.name = :schema AND t.name = :t AND c.name = :c
        """
    )
    with engine.begin() as conn:
        row = conn.execute(q, {"schema": schema, "t": table, "c": column}).mappings().first()
        if not row:
            return False
        dname = row["name"]
        conn.execute(
            text(f"ALTER TABLE [{schema}].[{table}] DROP CONSTRAINT [{dname}]")
        )
    return True


# ``ALTER COLUMN`` on datetime columns fails with 5074/4922 if these ``DF_*`` still exist
# (autogenerate often omits dropping them). Used by :func:`prepare_mssql_legacy_invoice_fks`.
MSSQL_DATETIME2_ALTER_DEFAULT_REMOVALS: tuple[tuple[str, str], ...] = (
    ("member_documents", "uploaded_at"),
    ("payment_bank_accounts", "created_at"),
    ("payment_banks", "created_at"),
    ("payment_mobile_providers", "created_at"),
    ("app_users", "last_login_at"),
    ("app_users", "last_seen_at"),
    ("contributions", "reversed_at"),
)


def engine_mssql_drop_defaults_that_block_datetime2_alter(
    engine, schema: str = "dbo"
) -> int:
    """Drop default constraints on known columns so ``ALTER COLUMN`` (DATETIME2 → DateTime) can run."""
    n = 0
    for table, column in MSSQL_DATETIME2_ALTER_DEFAULT_REMOVALS:
        if mssql_drop_default_constraint_on_column_if_exists(
            engine, table=table, column=column, schema=schema
        ):
            n += 1
    return n


def alembic_mssql_drop_default_on_column_if_exists(
    op, *, table: str, column: str, schema: str = "dbo"
) -> bool:
    return mssql_drop_default_constraint_on_column_if_exists(
        op.get_bind().engine, table=table, column=column, schema=schema
    )


def mssql_fk_name_exists(
    op, *, parent_table: str, constraint_name: str, schema: str = "dbo"
) -> bool:
    from sqlalchemy import text

    if "mssql" not in (op.get_bind().dialect.name or "").lower():
        return False
    q = text(
        """
        SELECT 1
        FROM sys.foreign_keys f
        INNER JOIN sys.tables pt
            ON f.parent_object_id = pt.object_id
        INNER JOIN sys.schemas s
            ON pt.schema_id = s.schema_id
        WHERE s.name = :schema
            AND pt.name = :t
            AND f.name = :cname
        """
    )
    b = op.get_bind()
    return b.execute(
        q, {"schema": schema, "t": parent_table, "cname": constraint_name}
    ).first() is not None


def alembic_mssql_ensure_utcdefault_if_missing(
    op, *, table: str, column: str, name: str | None = None, schema: str = "dbo"
) -> bool:
    """Re-add ``DEFAULT (sysutcdatetime())`` after a type change, if the column has no default yet."""
    from sqlalchemy import text

    if "mssql" not in (op.get_bind().dialect.name or "").lower():
        return False
    q = text(
        """
        SELECT dc.name
        FROM sys.default_constraints dc
        INNER JOIN sys.columns c
            ON dc.parent_object_id = c.object_id
            AND c.column_id = dc.parent_column_id
        INNER JOIN sys.tables t
            ON c.object_id = t.object_id
        INNER JOIN sys.schemas s
            ON t.schema_id = s.schema_id
        WHERE s.name = :schema
            AND t.name = :t
            AND c.name = :c
        """
    )
    b = op.get_bind()
    r = b.execute(
        q,
        {
            "schema": schema,
            "t": table,
            "c": column,
        },
    ).mappings().first()
    if r:
        return False
    cname = name or f"DF_{table}_{column}"
    if len(cname) > 128:
        cname = cname[:128]
    op.execute(
        text(
            f"ALTER TABLE [{schema}].[{table}]"
            f" ADD CONSTRAINT [{cname}]"
            f" DEFAULT (sysutcdatetime()) FOR [{column}];"
        )
    )
    return True


def alembic_mssql_drop_index_if_exists(op, *, table: str, index_name: str, schema: str = "dbo") -> None:
    from sqlalchemy import text

    if "mssql" not in (op.get_bind().dialect.name or "").lower():
        return
    op.execute(
        text(
            f"""
            IF EXISTS (
                SELECT 1
                FROM sys.indexes i
                INNER JOIN sys.tables t ON i.object_id = t.object_id
                INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
                WHERE s.name = N'{schema}' AND t.name = N'{table}' AND i.name = N'{index_name}'
            )
            DROP INDEX [{index_name}] ON [{schema}].[{table}];
            """
        )
    )
